apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-go-fgxwkxag
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/backend-tests-go-fgxwkxag:85ef46d44f84c3b0cfaf1de6c3f47f987c9a7a10@sha256:f2447af1da7509fd4a5bcabb5c84e1395a8c73dafae549fb5274b52ce1740486
          name: container-image
